file:
    namesPath: names.txt
    versionPath: service-config


springfox:
   documentation:
       swagger:
          v2:
             path: /swagger.json

endpoints:
  enabled: false
  health:
    enabled: true
  info:
    enabled: true


spring:
    jackson:
        serialization:
            INDENT_OUTPUT: true
logging:
  file: build/app.log
  level:
    ROOT: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.ws: DEBUG

info:
    config: Local