file:
    namesPath: names.txt
    versionPath: service-config

logging:
  file: build/app.log
  level: info

springfox:
   documentation:
       swagger:
          v2:
             path: /swagger.json

endpoints:
  enabled: false
  health:
    enabled: true
  info:
    enabled: true

spring:
    jackson:
        serialization:
            INDENT_OUTPUT: true
info:
    config: NFT

ibm:
  maximo:
    url: https://esls1uat.eu.smi.ibm.com/meaweb/services/MXISWOCHANGE
    user: gyowanny.pessattoqueiroz@shopdirect.com
    password: Viviana0906

amazon:
  dynamodb:
    endpoint: dynamodb.eu-west-1.amazonaws.com
    region: eu-west-1